# Generated by Django 3.2 on 2023-06-14 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=255)),
                ('desired_destination', models.CharField(max_length=255)),
                ('desired_course', models.CharField(max_length=255)),
                ('education_qualification', models.CharField(max_length=255)),
                ('inquiry_purpose', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': '01. Inquiries',
            },
        ),
    ]
