# Generated by Django 4.2.1 on 2023-06-19 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinquiry',
            name='purpose',
        ),
        migrations.DeleteModel(
            name='Purpose',
        ),
    ]
