# Generated by Django 4.2.1 on 2023-06-16 09:59

from django.db import migrations,models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='dob',
            field=models.DateField(auto_now=True),
        ),
    ]

