# Generated by Django 3.2 on 2023-06-14 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
