# Generated by Django 3.2 on 2023-06-19 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInquiryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_title', models.CharField(max_length=255)),
                ('note', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inquiry.studentinquiry')),
            ],
            options={
                'verbose_name_plural': '05. Inquiry Note',
            },
        ),
    ]
