# Generated by Django 4.2.1 on 2023-06-16 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0002_auto_20230616_1544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inquiry',
            old_name='institution',
            new_name='institution1',
        ),
        migrations.RenameField(
            model_name='inquiry',
            old_name='passed_year',
            new_name='passed_year1',
        ),
        migrations.RenameField(
            model_name='inquiry',
            old_name='percentage',
            new_name='percentage1',
        ),
        migrations.AddField(
            model_name='inquiry',
            name='institution2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='institution3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='passed_year2',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='passed_year3',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='percentage2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='percentage3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
