# Generated by Django 3.2 on 2023-06-19 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0002_studentinquirynote'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentInquiryNote',
            new_name='InquiryNote',
        ),
    ]
