# Generated by Django 3.2 on 2023-06-14 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0002_inquiry_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiry',
            name='contact_number',
        ),
        migrations.AddField(
            model_name='inquiry',
            name='address',
            field=models.CharField(default='sad', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inquiry',
            name='contact',
            field=models.CharField(default='asd', max_length=255),
            preserve_default=False,
        ),
    ]
