# Generated by Django 3.2 on 2023-06-14 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0003_auto_20230614_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiry',
            name='inquiry_purpose',
        ),
        migrations.AddField(
            model_name='inquiry',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
