# Generated by Django 3.2 on 2023-06-14 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0004_auto_20230614_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': '01. Inquiry Purpose',
            },
        ),
        migrations.AlterModelOptions(
            name='inquiry',
            options={'verbose_name_plural': '02. Inquiries'},
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='desired_course',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='desired_destination',
        ),
        migrations.AddField(
            model_name='inquiry',
            name='purpose',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inquiry.purpose'),
        ),
    ]
