# Generated by Django 3.2 on 2023-06-14 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0005_auto_20230614_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='InquiryStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': '02.  Stage',
            },
        ),
        migrations.AddField(
            model_name='inquiry',
            name='consultation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='stage',
            field=models.CharField(default='sd', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='purpose',
            field=models.CharField(default='sdad', max_length=255),
            preserve_default=False,
        ),
    ]
