# Generated by Django 3.2 on 2023-06-14 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0006_auto_20230614_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='source',
            field=models.CharField(default='sdad', max_length=255),
            preserve_default=False,
        ),
    ]
