# Generated by Django 3.2 on 2023-06-14 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0009_inquirynotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='closed_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
