# Generated by Django 3.2 on 2023-06-14 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0005_attendance_reason'),
        ('inquiry', '0010_inquiry_closed_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrm.employee'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
