# Generated by Django 4.2.1 on 2023-06-15 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0014_alter_inquiry_purpose'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiry',
            name='purpose',
        ),
    ]
