# Generated by Django 3.2 on 2023-05-28 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permission',
            old_name='create_products',
            new_name='create_course',
        ),
        migrations.RenameField(
            model_name='permission',
            old_name='delete_products',
            new_name='create_student',
        ),
        migrations.RenameField(
            model_name='permission',
            old_name='manage_products',
            new_name='delete_course',
        ),
        migrations.RenameField(
            model_name='permission',
            old_name='read_products',
            new_name='delete_student',
        ),
        migrations.RenameField(
            model_name='permission',
            old_name='update_products',
            new_name='manage_course',
        ),
        migrations.AddField(
            model_name='permission',
            name='manage_student',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='permission',
            name='read_course',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='permission',
            name='read_student',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='permission',
            name='update_course',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='permission',
            name='update_student',
            field=models.BooleanField(default=0),
        ),
    ]
