# Generated by Django 4.2.1 on 2023-06-02 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hrm', '0003_delete_logsheet'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': '03. Lead Sources',
            },
        ),
        migrations.CreateModel(
            name='LeadStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': '02. Lead Stage',
            },
        ),
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('lead_name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('contact', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('active', models.BooleanField(default=1)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ManyToManyField(to='hrm.employee')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.leadsource')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.leadstage')),
            ],
            options={
                'verbose_name_plural': '01. Leads',
            },
        ),
        migrations.CreateModel(
            name='LeadNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField()),
                ('leads', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.leads')),
            ],
            options={
                'verbose_name_plural': '06. Lead Notes',
            },
        ),
        migrations.CreateModel(
            name='LeadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_by', models.CharField(max_length=200)),
                ('activity', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.leads')),
            ],
            options={
                'verbose_name_plural': '04. Activity Log',
            },
        ),
        migrations.CreateModel(
            name='LeadFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='lead_file/')),
                ('added_by', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('leads', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.leads')),
            ],
            options={
                'verbose_name_plural': '06. Lead Files',
            },
        ),
        migrations.CreateModel(
            name='LeadCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=200)),
                ('called_by', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.leads')),
            ],
            options={
                'verbose_name_plural': '05. Lead Call',
            },
        ),
    ]
