# Generated by Django 3.2 on 2023-06-05 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20230528_0932'),
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads',
            name='course',
            field=models.ManyToManyField(to='course.Course'),
        ),
    ]
