# Generated by Django 3.2 on 2023-06-05 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_leads_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leads',
            name='course',
        ),
    ]
