# Generated by Django 4.2.1 on 2023-06-07 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_expensetype_alter_invoice_options_statement_receipt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='vat_amount',
        ),
    ]
