# Generated by Django 3.2 on 2023-06-13 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_remove_invoice_vat_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicecourse',
            name='course',
            field=models.CharField(blank=True, max_length=2555, null=True),
        ),
    ]
