# Generated by Django 3.2 on 2023-06-13 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_invoicecourse_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicecourse',
            name='course',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
