# Generated by Django 3.2 on 2023-06-19 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': '05. Department',
            },
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=255)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrm.department')),
            ],
            options={
                'verbose_name_plural': '05. Designation',
            },
        ),
        migrations.CreateModel(
            name='DeviceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=100)),
                ('port', models.IntegerField()),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('contact', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('emp_salary', models.CharField(blank=True, max_length=200, null=True)),
                ('emp_password', models.CharField(blank=True, max_length=200, null=True)),
                ('date_joined', models.DateTimeField(blank=True, null=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrm.department')),
                ('designation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrm.designation')),
                ('permission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.permission')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '01. Employees',
            },
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(max_length=100)),
                ('created', models.DateField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrm.employee')),
            ],
            options={
                'verbose_name_plural': '02. Leave',
            },
        ),
        migrations.CreateModel(
            name='MonthSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': '05. Month',
            },
        ),
        migrations.CreateModel(
            name='YearSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': '04. Year',
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_deduction', models.FloatField(blank=True, max_length=255, null=True)),
                ('tax_deduction', models.FloatField(blank=True, max_length=255, null=True)),
                ('company_deduction', models.FloatField(blank=True, max_length=255, null=True)),
                ('paid_salary', models.FloatField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, default='salary', max_length=255, null=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrm.employee')),
                ('month', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrm.monthsetup')),
            ],
            options={
                'verbose_name_plural': '03. Salary',
            },
        ),
        migrations.AddField(
            model_name='monthsetup',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrm.yearsetup'),
        ),
        migrations.CreateModel(
            name='LeaveDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=220)),
                ('leave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrm.leave')),
            ],
            options={
                'verbose_name_plural': '02. Leave Dates',
            },
        ),
        migrations.CreateModel(
            name='Holidays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holiday', models.DateField(blank=True)),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='hrm.monthsetup')),
            ],
            options={
                'verbose_name_plural': '05. Holiday',
            },
        ),
        migrations.CreateModel(
            name='DeviceAttendanceUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrm.employee')),
            ],
            options={
                'verbose_name_plural': '02. Attendance Users',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('half_day', 'Half Day')], max_length=20)),
                ('reason', models.TextField(blank=True, null=True)),
                ('is_opened', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrm.employee')),
            ],
            options={
                'verbose_name_plural': '02. Attendance',
            },
        ),
    ]
