# Generated by Django 4.2.1 on 2023-06-02 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0002_logsheet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogSheet',
        ),
    ]
