# Generated by Django 3.2 on 2023-07-07 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0002_logsheet_deviceattendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holidays',
            name='month',
        ),
        migrations.RemoveField(
            model_name='logsheet',
            name='user',
        ),
        migrations.DeleteModel(
            name='DeviceAttendance',
        ),
        migrations.DeleteModel(
            name='Holidays',
        ),
        migrations.DeleteModel(
            name='LogSheet',
        ),
    ]
