# Generated by Django 3.2 on 2023-07-10 05:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0003_auto_20230707_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
