# Generated by Django 3.2 on 2023-07-10 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0004_attendance_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
