# Generated by Django 3.2 on 2023-06-05 05:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0003_delete_logsheet'),
        ('course', '0002_auto_20230528_0932'),
        ('student', '0002_remove_student_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_type', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': '01. Enrollment Type',
            },
        ),
        migrations.CreateModel(
            name='StudentCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=200)),
                ('called_by', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': '05. Student Call',
            },
        ),
        migrations.CreateModel(
            name='StudentFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='Student_file/')),
                ('added_by', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': '06. Student Files',
            },
        ),
        migrations.CreateModel(
            name='StudentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_by', models.CharField(max_length=200)),
                ('activity', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': '04. Activity Log',
            },
        ),
        migrations.CreateModel(
            name='StudentNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField()),
            ],
            options={
                'verbose_name_plural': '06. Student Notes',
            },
        ),
        migrations.CreateModel(
            name='StudentSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': '03.  Sources',
            },
        ),
        migrations.CreateModel(
            name='StudentStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': '02.  Stage',
            },
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': '02. Student'},
        ),
        migrations.AddField(
            model_name='student',
            name='active',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='assigned_to',
            field=models.ManyToManyField(to='hrm.Employee'),
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.course'),
        ),
        migrations.AddField(
            model_name='student',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.AddField(
            model_name='studentnotes',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student'),
        ),
        migrations.AddField(
            model_name='studentlog',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student'),
        ),
        migrations.AddField(
            model_name='studentfiles',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student'),
        ),
        migrations.AddField(
            model_name='studentcall',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student'),
        ),
        migrations.AddField(
            model_name='student',
            name='enrollment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.enrollmenttype'),
        ),
        migrations.AddField(
            model_name='student',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.studentsource'),
        ),
        migrations.AddField(
            model_name='student',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.studentstage'),
        ),
    ]
