# Generated by Django 3.2 on 2023-06-05 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20230605_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='log_status',
            field=models.BooleanField(default=True),
        ),
    ]
