# Generated by Django 3.2 on 2023-06-13 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20230605_1226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentnotes',
            old_name='notes',
            new_name='note',
        ),
        migrations.AddField(
            model_name='studentnotes',
            name='note_title',
            field=models.CharField(default='sdsa', max_length=255),
            preserve_default=False,
        ),
    ]
