# Generated by Django 3.2 on 2023-06-19 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hrm', '0005_attendance_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='InquiryPurpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': '02.  Stage',
            },
        ),
        migrations.CreateModel(
            name='InquiryStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': '02.  Stage',
            },
        ),
        migrations.CreateModel(
            name='StudentInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('dob', models.DateField(auto_now=True)),
                ('guardian_name', models.CharField(max_length=255)),
                ('marital_status', models.CharField(default='Single', max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=255)),
                ('temporary_address', models.CharField(max_length=255)),
                ('permanent_address', models.CharField(max_length=255)),
                ('institution1', models.CharField(blank=True, max_length=100, null=True)),
                ('passed_year1', models.PositiveIntegerField(blank=True, null=True)),
                ('percentage1', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('institution2', models.CharField(blank=True, max_length=100, null=True)),
                ('passed_year2', models.PositiveIntegerField(blank=True, null=True)),
                ('percentage2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('institution3', models.CharField(blank=True, max_length=100, null=True)),
                ('passed_year3', models.PositiveIntegerField(blank=True, null=True)),
                ('percentage3', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('course', models.CharField(default=True, max_length=100)),
                ('college', models.CharField(default=True, max_length=100)),
                ('country', models.CharField(default=True, max_length=100)),
                ('city', models.CharField(default=True, max_length=100)),
                ('intake', models.CharField(default=True, max_length=100)),
                ('applied_country', models.CharField(blank=True, max_length=100, null=True)),
                ('applied_date', models.DateField(blank=True, null=True)),
                ('other', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('assigned', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrm.employee')),
                ('purpose', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='studentinquiry.inquirypurpose')),
            ],
            options={
                'verbose_name_plural': '03. Inquiries',
            },
        ),
        migrations.CreateModel(
            name='InquiryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_title', models.CharField(max_length=255)),
                ('note', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentinquiry.studentinquiry')),
            ],
            options={
                'verbose_name_plural': '05. Inquiry Note',
            },
        ),
        migrations.CreateModel(
            name='InquiryLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_by', models.CharField(max_length=200)),
                ('activity', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentinquiry.studentinquiry')),
            ],
            options={
                'verbose_name_plural': '04. Inquiry Logs',
            },
        ),
    ]
