# Generated by Django 3.2 on 2023-07-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentinquiry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinquiry',
            name='source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentinquiry',
            name='test',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
