# Generated by Django 3.2 on 2023-06-19 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentinquiry', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inquirypurpose',
            options={'verbose_name_plural': '02.  purpose'},
        ),
        migrations.RenameField(
            model_name='inquirypurpose',
            old_name='stage',
            new_name='purpose',
        ),
    ]
