# Generated by Django 3.2 on 2023-07-19 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentinquiry', '0002_auto_20230710_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinquiry',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='studentinquiry.inquirystage'),
        ),
    ]
