# Generated by Django 3.2 on 2023-06-19 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentinquiry', '0003_alter_studentinquiry_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinquiry',
            name='applied_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
