# Generated by Django 3.2 on 2023-07-19 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentinquiry', '0003_studentinquiry_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinquiry',
            name='purpose',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='studentinquiry.inquirypurpose'),
        ),
        migrations.AlterField(
            model_name='studentinquiry',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='studentinquiry.inquirystage'),
        ),
    ]
