# Generated by Django 4.1.4 on 2023-07-20 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentinquiry', '0004_auto_20230719_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinquiry',
            name='institution4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentinquiry',
            name='passed_year4',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentinquiry',
            name='percentage4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
