# Generated by Django 4.2.1 on 2023-06-20 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentinquiry', '0005_studentinquiry_closed_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinquiry',
            name='closed_reason',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
