# Generated by Django 3.2 on 2023-07-07 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentinquiry', '0006_alter_studentinquiry_closed_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinquiry',
            name='closed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
