# Generated by Django 3.2 on 2023-05-24 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('company_address', models.CharField(max_length=255)),
                ('company_email', models.CharField(max_length=255)),
                ('company_contact_number', models.CharField(max_length=255)),
                ('company_logo', models.ImageField(upload_to='company_images/')),
                ('payment_terms', models.TextField()),
                ('payment_details', models.TextField()),
                ('created', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': '03. Company Setup',
            },
        ),
        migrations.RemoveField(
            model_name='document',
            name='course',
        ),
        migrations.RemoveField(
            model_name='document',
            name='student',
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='course',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='student',
        ),
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='Enrollment',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
