# Generated by Django 3.2 on 2023-07-20 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_employeenotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeenotification',
            name='status',
            field=models.CharField(default='unread', max_length=244),
        ),
    ]
