# Generated by Django 3.2 on 2023-06-12 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0005_attendance_reason'),
        ('features', '0003_remove_company_payment_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('task_title', models.CharField(max_length=255)),
                ('task', models.TextField()),
                ('deadline', models.CharField(max_length=255)),
                ('task_from', models.CharField(max_length=255)),
                ('priority', models.CharField(max_length=255)),
                ('status', models.CharField(default='incomplete', max_length=255)),
                ('task_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrm.employee')),
            ],
            options={
                'verbose_name_plural': '02. To Do',
            },
        ),
    ]
